version: '2'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - /etc/nginx/website:/usr/share/nginx/html:ro
      - /etc/nginx/nginx1.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/sites-enabled/borys:/etc/nginx/conf.d/default.conf:ro
      - /etc/nginx/blacklist.conf:/etc/nginx/blacklist.conf:ro
      - /etc/nginx/blockips.conf:/etc/nginx/blockips.conf:ro
    network_mode: bridge
    ports:
      - 80:80
    environment:
      - NGINX_HOST='borys.dynu.net'
